---
- name: Deploying Review Radar on the kubernetes cluster
  hosts: localhost
  remote_user: anjali
  become: false
  tasks:       
    - name: Deploying application to kubernetes cluster
      ansible.builtin.shell: |
        kubectl apply -f ../k8s/deploy/backend-deploy.yml
        kubectl apply -f ../k8s/deploy/frontend-deploy.yml
        kubectl apply -f ../k8s/services/backend-service.yml
        kubectl apply -f ../k8s/services/frontend-service.yml
        kubectl apply -f ../k8s/ingress/ingress.yml
