---
- name: Deploying Review Radar on the kubernetes cluster
  hosts: localhost
  remote_user: anjali
  become: false
  tasks:
    - name: Set Kubernetes context
      ansible.builtin.shell: kubectl config use-context minikube
      
    - name: Deleting older application files
      ansible.builtin.shell: |
        kubectl delete -f ../k8s/deploy/backend-deploy.yml --ignore-not-found=true
        kubectl delete -f ../k8s/deploy/frontend-deploy.yml --ignore-not-found=true
        kubectl delete -f ../k8s/services/backend-service.yml --ignore-not-found=true
        kubectl delete -f ../k8s/services/frontend-service.yml --ignore-not-found=true
        kubectl delete -f ../k8s/ingress/ingress.yml --ignore-not-found=true
        
    - name: Deploying application to kubernetes cluster
      ansible.builtin.shell: |
        kubectl apply -f ../k8s/deploy/backend-deploy.yml
        kubectl apply -f ../k8s/deploy/frontend-deploy.yml
        kubectl apply -f ../k8s/services/backend-service.yml
        kubectl apply -f ../k8s/services/frontend-service.yml
        kubectl apply -f ../k8s/ingress/ingress.yml
